name: hello_world
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
 
  image: ^4.1.3  # Add this line (check for latest version)
  web_socket_channel: ^2.4.0  # Use the latest version from pub.dev
  path_provider: ^2.0.14 # Use the latest version available
  permission_handler: ^10.2.0
  speech_to_text: ^6.6.2  # Ensure this is the latest version
  speech_to_text_platform_interface: ^2.3.0  # Ensure this is the latest version
  flutter_tts: ^3.5.0
  google_ml_kit: ^0.19.0
  image_picker: ^0.8.7
  google_mlkit_text_recognition: ^0.14.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  camera: ^0.11.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1 

flutter:
  uses-material-design: true
#dev_dependencies:
  # Ensure this is the latest version
  # Custom fonts section
  fonts:
    - family: OpenDyslexic
      fonts:
        - asset: assets\fonts\open-dyslexic.ttf
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"  # Path to your icon file
  adaptive_icon_background: "#ffffff" # (optional) Background for adaptive icons (Android)
  adaptive_icon_foreground: "assets/icon/icon.png"  # (optional) Foreground for adaptive icons (Android)

  # Uncomment the assets section if you want to add images or other resources
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


# name: hello_world
# description: "A new Flutter project."
# publish_to: 'none'

# version: 1.0.0+1

# environment:
#   sdk: '>=3.2.6 <4.0.0'

# dependencies:
#   flutter:
#     sdk: flutter
  
#   image: ^4.1.3
#   web_socket_channel: ^2.4.0
#   path_provider: ^2.0.14
#   permission_handler: ^10.2.0
#   speech_to_text: ^6.6.2
#   speech_to_text_platform_interface: ^2.3.0
#   flutter_tts: ^3.5.0
#   google_ml_kit: ^0.19.0
#   image_picker: ^0.8.7
#   google_mlkit_text_recognition: ^0.14.0
#   cupertino_icons: ^1.0.2
#   camera: ^0.11.0+1

# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   flutter_lints: ^4.0.0
#   flutter_launcher_icons: ^0.13.1  # Ensure this is the latest version

# flutter:
#   uses-material-design: true
  
#   assets:
#     - assets/icon/icon.png  # Ensure this exists
#     - assets/fonts/open-dyslexic.ttf  # Ensure this exists

#   fonts:
#     - family: OpenDyslexic
#       fonts:
#         - asset: assets/fonts/open-dyslexic.ttf

# flutter_icons:
#   android: true
#   ios: true
#   image_path: "assets/icon/icon.png"  
#   adaptive_icon_background: "#ffffff"  
#   adaptive_icon_foreground: "assets/icon/icon.png"
